In [16]:
import pandas as pd

df = pd.read_csv("../data/raw/events.csv")
df.head()

,city,city_tier,event_type,guest_count,season,lead_time_days,budget,has_live_music,has_alcohol,is_outdoor,is_destination,venue_pct,catering_pct,decor_pct,photography_pct,music_pct,invites_pct,transport_pct,contingency_pct
0,Nagpur,2,birthday,302,1,93,225490,0,1,0,0,0.086862,0.131597,0.200610,0.176496,0.056506,0.200905,0.087453,0.059572
1,Pune,2,corporate,455,0,130,714498,0,0,0,1,0.029334,0.094089,0.125946,0.107585,0.177298,0.268148,0.132900,0.064699
2,Kolhapur,3,corporate,482,1,173,676302,0,1,1,0,0.050418,0.039675,0.140559,0.037042,0.013426,0.080857,0.522455,0.115569
3,Belgaum,3,corporate,486,0,64,693992,1,1,0,0,0.146753,0.256916,0.079105,0.074773,0.205981,0.178620,0.053719,0.004133
4,Delhi,1,festival,367,1,36,530005,1,1,0,1,0.236617,0.106037,0.066784,0.031774,0.003338,0.026030,0.087420,0.442000

In [17]:
split_cols = [col for col in df.columns if "_pct" in col]
df[split_cols].sum(axis=1).head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

In [18]:
df.groupby("event_type")["budget"].mean()

event_type
anniversary    316874.392405
birthday       258965.885794
corporate      469163.789174
engagement     667000.521036
festival       380133.349254
wedding        940694.427273
Name: budget, dtype: float64

In [19]:
df.groupby("city_tier")["budget"].mean()

city_tier
1    567564.313559
2    485663.872253
3    436623.602837
Name: budget, dtype: float64

In [20]:
df.groupby("event_type")[["guest_count", "budget"]].mean()

             guest_count         budget
event_type
anniversary   276.129747  316874.392405
birthday      284.660167  258965.885794
corporate     274.564103  469163.789174
engagement    292.236246  667000.521036
festival      275.976119  380133.349254
wedding       274.130303  940694.427273